### ISSUE TITLE
Insert Date key binding conflicts with built-in Sublime Text command

### ISSUE THREAD

**Issue by sentience** [23maverick23/sublime-jekyll#24]
In Sublime Text, **⌘K, ⌘D** by default is bound to the `find_under_expand_skip` command, which expands a multiple selection to include the next instance of the currently-selected text, and removes the current instance from the selection. This is also known as the “Quick Skip Next” command. You can read an example of how it is used here: http://www.sublimetext.com/docs/3/multiple_selection_with_the_keyboard.html

Personally I’m able to remap this key combination back to the default command, which I use frequently, but I wonder if it’s wise to override default key bindings like these?

**Comment by dsernst** [comment]
Thank you for fixing this! :+1:

**Comment by 23maverick23** [comment]
@dsernst My pleasure! Sorry it took so long - I've been busy with work, travel and holidays. Enjoy.

**Comment by sentience** [comment]
Glad this was fixed. I have no issue with removing the clashing key bindings.
