### ISSUE TITLE
New Post fails when using "default_post_extras"

### ISSUE THREAD

**Issue by jcornelius** [23maverick23/sublime-jekyll#25]
Adding key: value pairs to `default_post_extras` causing Post builds to fail in ST2.

Line 55 of Jekyll.sublime-settings
```
"default_post_extras": {"key": "value"},
```

Console log.
```
reloading /Users/jc/Library/Application Support/Sublime Text 2/Packages/User/Jekyll.sublime-settings
Traceback (most recent call last):
  File "./jekyll.py", line 231, in title_input
  File "./jekyll.py", line 189, in create_post_frontmatter
  File "./jekyll.py", line 186, in pretty_walk
  File "./jekyll.py", line 183, in walk
ValueError: zero length field name in format
```

**Comment by 23maverick23** [comment]
@jcornelius Thanks for sending this over! Update to v2.1.3 once it's available and let me know if that fixes it.

Looks like a Python 2.6 requires position arguments in string formats - [reference](http://stackoverflow.com/a/8498327)

**Comment by jcornelius** [comment]
@23maverick23 Thanks for the quick fix. When will 2.1.3 be up?

**Comment by jcornelius** [comment]
@23maverick23 Fixed! Thanks.
