### ISSUE TITLE
Jekyll: Unable to find path information in Jekyll.sublime-settings

### ISSUE THREAD

**Issue by dverloc** [23maverick23/sublime-jekyll#26]
Hey-

I'm trying to set up the sublime text package and need some assistance. I'm getting an error (Jekyll: Unable to find path information in Jekyll.sublime-settings). I thought I configured the paths correctly, but obviously not. Can you help? I'm new and not sure where to start troubleshooting beyond what I've already looked at.

Here is what is included in my Jekyll.sublime-settings file:

{

	// This should point to your "_posts" directory.
    // NOTE: This should be an absolute path. Also, the path should
    // match your system convention. For example, Windows machines should
    // have a path similar to "C:\\Users\\username\\site\\_posts".
    // *nix systems should have a path similar to "/Users/username/site/_posts".
    "posts_path": "/Users/dmabee/testProj/_posts",

    // This should point to your "_drafts" directory.
    // NOTE: This should be an absolute path. Also, the path should
    // match your system convention. For example, Windows machines should
    // have a path similar to "C:\\Users\\username\\site\\_drafts".
    // *nix systems should have a path similar to "/Users/username/site/_drafts".
    "drafts_path": "/Users/dmabee/testProj/_drafts",

    // This string value should represent the default syntax for a new post.
    // Valid options are: "Markdown", "Textile"
    "default_post_syntax": "Markdown",

    /** *****************************************************************************
     * Post Front-matter Defaults
     *
     * Set these values to make your life easier when composing new posts. This is
     * similar to setting your defaults as part of the `_config.yml` file:
     *
     * http://jekyllrb.com/docs/configuration/#front-matter-defaults
     * ******************************************************************************
     */

    // This string value should represent the default layout for new posts.
    "default_post_layout": "page",

    // This value should represent the default categories for new posts.
    // Each category should be entered as a list item in string format
    // with commas separating values ["cat1", "cat2"]. To remove this key
    // from your front-matter completely, pass a value of `null`.
    "default_post_categories": [],

    // This value should represent the default tags for new posts.
    // Each tag should be entered as a list item in string format
    // with commas separating values ["tag1", "tag2"]. To remove this key
    // from your front-matter completely, pass a value of `null`.
    "default_post_tags": [],

    // A boolean specifying if you want new posts to be marked as published.
    // To remove this key from your front-matter completely, pass a value of `null`.
    "default_post_published": true,

    // If you need to add additional front-matter `key: value` information to
    // your posts, you can store them in a dictionary object using a format
    // like {"foo": "bar", "baz": "qux"}. This dictionary will be appended to
    // any of the enabled default keys above (Reminder: the `title` and `layout`
    // keys will always be included, so **DO NOT** include them in the extras dictionary).
    "default_post_extras": {},

    /** ***********************************************************************************
     * If for some reason you want to change the way either the date
     * or the datetime string is formatted, you can override those formats
     * here using valid Python datetime.strftime() format codes.
     *
     * If you need a refresher on these codes, have a look at the Python
     * documentation found here:
     *
     * http://docs.python.org/2/library/datetime.html#strftime-and-strptime-behavior
     * ******************************************************************************
     */

    // A valid Python strftime string
    "insert_date_format": "%Y-%m-%d",

    // A valid Python strftime string
    "insert_datetime_format": "%Y-%m-%d %H:%M:%S",

    "folders":
    [
        {
            "follow_symlinks": true,
            "path": "/Users/dmabee/testProj"
        }
    ],

    "settings":
    {
        "Jekyll":
        {
            "posts_path": "/Users/dmabee/testProj/_posts",
            "drafts_path": "/Users/dmabee/testProj/_drafts",
        }
    },

	"ignored_packages":
	[
		"Vintage"
	]

}

**Comment by 23maverick23** [comment]
@dverloc What platform are you on (Windows, Mac, Linux)? The format in the suggestions/notes are for Unix, so if you're on Windows you'd need to update. Also, that `Jekyll.sublime-settings` file doesn't look correct. It looks like you're combing your "user" settings with your "project" settings. Project settings go inside your `<project name>.sublime-project` file (which is created when you save a new project) - [more info here](https://www.sublimetext.com/docs/2/projects.html).

Can you open the console <kbd>Ctrl</kbd>+<kbd>~</kbd> and let me know if you see anything related to sublime-jekyll in there?

**Comment by dverloc** [comment]
I'm on a Mac. Initially i put it into the User settings file but have since removed. I have it in a file called Jekyll.sublime-settings:

{

	// This should point to your "_posts" directory.
    // NOTE: This should be an absolute path. Also, the path should
    // match your system convention. For example, Windows machines should
    // have a path similar to "C:\\Users\\username\\site\\_posts".
    // *nix systems should have a path similar to "/Users/username/site/_posts".
    "posts_path": "/Users/dmabee/testProj/_posts",

    // This should point to your "_drafts" directory.
    // NOTE: This should be an absolute path. Also, the path should
    // match your system convention. For example, Windows machines should
    // have a path similar to "C:\\Users\\username\\site\\_drafts".
    // *nix systems should have a path similar to "/Users/username/site/_drafts".
    "drafts_path": "/Users/dmabee/testProj/_drafts",

    // This string value should represent the default syntax for a new post.
    // Valid options are: "Markdown", "Textile"
    "default_post_syntax": "Markdown",

    /** *****************************************************************************
     * Post Front-matter Defaults
     *
     * Set these values to make your life easier when composing new posts. This is
     * similar to setting your defaults as part of the `_config.yml` file:
     *
     * http://jekyllrb.com/docs/configuration/#front-matter-defaults
     * ******************************************************************************
     */

    // This string value should represent the default layout for new posts.
    "default_post_layout": "page",

    // This value should represent the default categories for new posts.
    // Each category should be entered as a list item in string format
    // with commas separating values ["cat1", "cat2"]. To remove this key
    // from your front-matter completely, pass a value of `null`.
    "default_post_categories": [],

    // This value should represent the default tags for new posts.
    // Each tag should be entered as a list item in string format
    // with commas separating values ["tag1", "tag2"]. To remove this key
    // from your front-matter completely, pass a value of `null`.
    "default_post_tags": [],

    // A boolean specifying if you want new posts to be marked as published.
    // To remove this key from your front-matter completely, pass a value of `null`.
    "default_post_published": true,

    // If you need to add additional front-matter `key: value` information to
    // your posts, you can store them in a dictionary object using a format
    // like {"foo": "bar", "baz": "qux"}. This dictionary will be appended to
    // any of the enabled default keys above (Reminder: the `title` and `layout`
    // keys will always be included, so **DO NOT** include them in the extras dictionary).
    "default_post_extras": {},

    /** ***********************************************************************************
     * If for some reason you want to change the way either the date
     * or the datetime string is formatted, you can override those formats
     * here using valid Python datetime.strftime() format codes.
     *
     * If you need a refresher on these codes, have a look at the Python
     * documentation found here:
     *
     * http://docs.python.org/2/library/datetime.html#strftime-and-strptime-behavior
     * ******************************************************************************
     */

    // A valid Python strftime string
    "insert_date_format": "%Y-%m-%d",

    // A valid Python strftime string
    "insert_datetime_format": "%Y-%m-%d %H:%M:%S",

    "folders":
    [
        {
            "follow_symlinks": true,
            "path": "/Users/dmabee/testProj"
        }
    ],

    "settings":
    {
        "Jekyll":
        {
            "posts_path": "/Users/dmabee/testProj/_posts",
            "drafts_path": "/Users/dmabee/testProj/_drafts",
        }
    }

}

My Jekyll.sublime-project looks like this:

{
	"folders":
	[
		{
			"follow_symlinks": true,
			"path": "/Users/dmabee/testProj"
		}
	]
}

Here is the most recent info from the console. When I attempt to run Jekyll through the Command Palette, I don't see anything happen (but there isn't an error any more either).

**Comment by 23maverick23** [comment]
@dverloc Thanks for providing the console log info - very helpful. There's definitely an error happening when trying to create your posts path at [Line 225](https://github.com/23maverick23/sublime-jekyll/blob/master/jekyll.py#L225).

Are you sure that the path you have - `/Users/dmabee/testProj/_posts` - is a valid path? If you open up Terminal and try to `cd` into that does it work?

To be honest, I didn't build very robust error catching into this plugin, so we may need to go back and forth on debugging this together :relaxed:

**Comment by Fastidious** [comment]
Same problem here. Was this ever fixed?

**Comment by 23maverick23** [comment]
@Fastidious - Can you give some additional details to help me debug?

What error message are you seeing?
Do you have any error outputs in the Sublime console?
Can you attach your full sublime-settings file?
What version of Sublime and which platform are you running?

**Comment by Fastidious** [comment]
My apologies, disregard. I was using main settings for the plugin variables, without realizing the plugin has its own settings file. Used that one and works fine.

**Comment by fbarbalho** [comment]
Just copy the informations from Settings Deffault to Settings User, and alter the information about posts path.
