### ISSUE TITLE
Per Project Settings

### ISSUE THREAD

**Issue by allejo** [23maverick23/sublime-jekyll#28]
In the README, it says that I can have per-project settings since I'm maintaining multiple Jekyll sites but how do I do that? The README says to "make sure you add your Jekyll settings correctly" but I'm not sure how that works. Do I add a separate file to my Jekyll site where it'll have the settings for this plug-in or does it read the _config.yml?

**Comment by 23maverick23** [comment]
Hey @allejo - thanks for using the plugin!

Have a look at [issue #16](https://github.com/23maverick23/sublime-jekyll/issues/16) - that should hopefully clear it up for you. If you have additional questions, let me know.

**Comment by allejo** [comment]
Ah thanks! Sorry about not doing a good job searching before I asked. I do have one more question though, when defining the values, are they relative to the project or do I need to specify the full path? If I specify the full path, moving the project elsewhere would become a burden and it doesn't seem to work if I try `./_posts` or `_posts`.

**For example:**

```json
{
    "folders":
    [
        {
            "follow_symlinks": true,
            "path": "."
        }
    ],

    "settings":
    {
        "Jekyll":
        {
            "posts_path": "_posts",
            "drafts_path": "_drafts"
        }
    }
}
```

**Comment by 23maverick23** [comment]
Glad that helped, @allejo . The current implementation requires a full path for those dict keys, which is a pain if you plan to move your projects around a lot (or share them across machines).

I'm hoping to release v2.2.0 soon which will optionally allow Sublime to "find" the correct folder in your Jekyll project automatically, without specifying a path in either the User or Project settings. Stay tuned!

**Comment by allejo** [comment]
Thanks for the clarification! Yea, I share a project among different machines so I look forward to v2.2.0!

**Comment by allejo** [comment]
Is the `automatically_find_paths` option meant only to be set in the package's setting or can it be done on a per-project basis? I can only get it to work as a setting for the actual package.
