### ISSUE TITLE
Hyphens in HTML (Jekyll) are breaking syntax highlighting

### ISSUE THREAD

**Issue by jamiewilson** [23maverick23/sublime-jekyll#38]
First off, I love this plugin. it's just what I was looking for—for jekyll and for liquid syntax highlighting in general. Thank you! But I've run into a problem with hyphenated words breaking syntax highlighting:

![screen shot 2015-07-14 at 11 46 59 am](https://cloud.githubusercontent.com/assets/3308673/8679129/691c4498-2a1e-11e5-9f38-424070d88f88.png)

Any ideas on how I can prevent this from happening?

**Comment by 23maverick23** [comment]
Thanks for using it @jamiewilson !

I'm actually looking into re-writing all the syntax logic to actually allow the user to specify a syntax (e.g. MultiMarkdown or something like [Markdown Editing](https://packagecontrol.io/packages/MarkdownEditing) ), or use the standard with this package. My custom syntaxes are pretty bad I think :wink: .

I could also probably fork some of the better syntax packages out there and incorporate them into my package (with credit). I'm planning on a new updated version later this year. I'll see if I can look at this and provide a fix, but it might be more complicated (syntax files in Sublime Text actually kind of suck).

**Comment by 23maverick23** [comment]
@jamiewilson Just curious - what color scheme are you using? I can't tell from the screenshot. I just tested the same code on my machine using Tomorrow-Night theme and it works as I would expect.

![screen shot 2015-07-14 at 8 26 00 pm](https://cloud.githubusercontent.com/assets/905119/8688207/4bd45d0a-2a67-11e5-8219-0b599b813381.png)

**Comment by jamiewilson** [comment]
Ah. good point. I'm using my own color scheme called [Predawn](https://packagecontrol.io/packages/Predawn). :/ 

I had poked around my syntax highlighting scopes before posting this issue, but didn't see anything that would apply to the hyphenation. I tested it with [siteleaf/liquid-syntax-mode](https://github.com/siteleaf/liquid-syntax-mode) and it highlighted correctly. Could very well be my theme though. I'll keep looking into though.

**Comment by jamiewilson** [comment]
Hmm. doesn't seem to be my color scheme. Setting syntax to plain HTML fixed the issue. It must be some conflict sublime-jekyll and another package. Here's what it looks like with Monokai:

![screen shot 2015-07-21 at 4 19 55 pm](https://cloud.githubusercontent.com/assets/3308673/8812897/8e756322-2fc4-11e5-8ce1-75e9f15446c7.png)

I'll keep playing around to see if I can isolate the problem. What version

**Comment by Haroenv** [comment]
I see this too in base16-eighties-dark on 3083

**Comment by 23maverick23** [comment]
Just a quick update for @jamiewilson and @Haroenv ...

Although I don't plan on adding these syntax files to the 3.0 version of the package, I will move the syntax files to a new, separate repo and allow the community to submit PRs for fixes. I took a very (very) quick look at this one, and I think the error lies somewhere in [L237-L279](https://github.com/23maverick23/sublime-jekyll/blob/master/Syntaxes/HTML%20(Jekyll).JSON-tmLanguage#L237-L279) of the `.JSON-tmLanguage` file, likely around capture 4 or 11. I tossed it into a regex tester and can see the issue you both reported [here](https://regex101.com/r/mY7tG7/1).

I'll take a look at this when I move the files over to the new repo and see if I can patch a fix. Like I mentioned in my original comment - I absolutely hate ST syntax files :wink:
The amount of regex you have to write just to highlight a single letter makes my head spin!
