### ISSUE TITLE
Syntax highlighting inside highlight block? Kramdown?

### ISSUE THREAD

**Issue by aldanor** [23maverick23/sublime-jekyll#39]
Could the code inside `{% highlight lang options %}` be possible syntax highlighted? (sort of like javascript code is highlighted in html files)

For Kramdown, you can write

```markdown
{:.myclass} {% highlight python %}
print 'foo'
{% endhighlight %}
```

-- however this completely breaks syntax highlighting for the `{% highlight %}` section.

**Comment by 23maverick23** [comment]
Hey @aldanor My relatively simple syntax files don't have support for embedded syntax highlighting today. I'm thinking of re-writing the next version of this plugin to allow the use of custom syntax files (there are lots of options out there for markdown that support things like syntax highlighting and GTD).

**Comment by danielcorin** [comment]
:+1:
