### ISSUE TITLE
Multi line front matter in default_post_extras

### ISSUE THREAD

**Issue by sukhdeepsingh** [23maverick23/sublime-jekyll#40]
Hi, Thanks for the nice package, I have just started using it.
How can I configure the "default_post_extras" variable to have a multiline indented tag eg
I want this to be injected in my each blog posts front matter and in the same order (as the order also gets jumbled up in the new post when I create)

```
image:
  feature: image.jpg
  credit: @singh
  creditlink: 
```
I tried 
```
"default_post_extras": {"excerpt":"","comments":"True","image":"","feature":"","credit":"","creditlink":"","link":""},
```
and then I tried
```
 "default_post_extras": {"excerpt":"","comments":"True","link":""},
 "default_post_extras": {"image":"","feature":"","credit":"","creditlink":""},
```
Please help.
Thanks

**Comment by 23maverick23** [comment]
Hey @sukhdeepsingh - thanks!

You should be able to get the desired format using another dictionary as a key value for your `image` section like this:

```json
"default_post_extras": {
    "excerpt": "", "comments": "True", "image": {
        "feature": "", "credit": "", "creditlink":"", "link":""
    }
}
```

When you create your post, it should translate to this:
![screen shot 2015-07-31 at 8 43 33 am](https://cloud.githubusercontent.com/assets/905119/9007545/49ae1cb8-3760-11e5-83e8-b4ccecc7e212.png)

**Comment by sukhdeepsingh** [comment]
Thanks, that worked great. Just on this point, why the order is not maintained. For eg. look at the ```excerpt``` tag, we added it as the top key, but it became second last in the post file. How can I maintain the order.

**Comment by 23maverick23** [comment]
Curious - why does your YAML front matter key order matter? Aesthetics?

Python sets (dictionaries) are unordered by definition, so there is never a guarantee that the order you insert the values are the order they come out (more here: http://stackoverflow.com/a/15479974).

The implementation I am using is a simple dictionary walk - you can have a look here if you have suggestions on improvements: https://github.com/23maverick23/sublime-jekyll/blob/master/jekyll.py#L212-L242 . I could maybe look at using `OrderedDict` in conjunction, but I haven't seen a need for that.

**Comment by sukhdeepsingh** [comment]
Thanks for your time Ryan, no pressing issues just the aesthetics as you said :)

**Comment by 23maverick23** [comment]
Np. I'll put it on the backlog and see if I can get to it on my next major release. Thanks for the feedback!
