### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by EvanBindz** [23maverick23/sublime-jekyll#51]
\<p>Source: \<a href="{{page.source}}">{{page.source}}\</a>\</p>

'Source:' should just be text but is recognized as a command in syntax highlighting

**Comment by 23maverick23** [comment]
Thx for bringing this up.

I'm currently working on v3.0 of this package, and I'm planning on deprecated the syntax highlighting (mainly b/c there are much better packages out there to provide Markdown highlighting). If you'd like to submit a PR for this issue, please feel free :smile:
