### ISSUE TITLE
Recognises colon as keyword

### ISSUE THREAD

**Issue by Haroenv** [23maverick23/sublime-jekyll#52]
![](https://i.imgur.com/lOMYWpH.png)

theme: base16-eighties-dark
build: 3083

The colon should only mean a keyword wrapped in `{{}}` or `{%%}`.

**Comment by 23maverick23** [comment]
Thx for bringing this up.

I commented on #51 as well, but I'm currently working on v3.0 of this package, and I'm planning on deprecating the syntax highlighting (mainly b/c there are much better packages out there to provide Markdown highlighting). If you'd like to submit a PR for this issue, please feel free!

**Comment by Haroenv** [comment]
I must say that I was mainly interested in the highlighting, what alternative highlighting package do you use? or do you just use language: html?

**Comment by 23maverick23** [comment]
@Haroenv Sorry to disappoint. They aren't completely gone, however. I've moved them to an independent repo here - https://github.com/23maverick23/sublime-jekyll-syntaxes/ .

You should be able to just fork or download the repo and copy/paste the `.tmLanguage` files directly into your Packages/User directory and restart Sublime. If you want to try other packages, I believe Django uses a version of Liquid templating and the `Djanerio` package has an HTML syntax file you could try (https://github.com/squ1b3r/Djaneiro/tree/master/Syntaxes).

If I get around to it (or if you wanted to submit a PR), I'll look at improving the syntax files I originally built 2 years ago and try to release them on Package Control as another package.

**Comment by Haroenv** [comment]
That'd be cool, I also noticed that twig is kinda similar, so those syntax files could be a help too. I'll give this a look when I find time for it.

**Comment by 23maverick23** [comment]
You can also try out https://github.com/siteleaf/liquid-syntax-mode . It hasn't been updated in a while, but it may be worth a look :wink:
