### ISSUE TITLE
Where's the 'HTML (Jekyll)' language package?

### ISSUE THREAD

**Issue by seshaljain** [23maverick23/sublime-jekyll#55]
Before the new update, the package used to add an `HTML (Jekyll)` package. Was it removed? If so, do bring it back!

![image](https://cloud.githubusercontent.com/assets/11702800/12717519/6707a4ec-c90e-11e5-939d-65cda2a3b9fa.png)

Now it shows only `HTML`, so no syntax highlighting for Jekyll and Liquid tags!

**Comment by 23maverick23** [comment]
Hey @seshaljain Thanks for upgrading to v3.0.

I made a decision (it wasn't easy) to remove the syntax files from the package entirely, and allow everyone to use whatever syntax they want. This was really important for people using Markdown. They aren't completely gone, however. I've moved them to an independent repo here - https://github.com/23maverick23/sublime-jekyll-syntaxes/ .

You should be able to just fork or download the repo and copy/paste the `.tmLanguage` files directly into your `Packages/User` directory and restart Sublime. If you want to try other packages, I believe Django uses a version of Liquid templating and the `Djanerio` package has an HTML syntax file you could try (https://github.com/squ1b3r/Djaneiro/tree/master/Syntaxes).
