### ISSUE TITLE
No option for syntax higlighting after installation

### ISSUE THREAD

**Issue by klomontes** [23maverick23/sublime-jekyll#56]
I've been using this plugin for quite some time but at one point syntax highlighting option disappeared. I tried uninstalling and installing it again both via Package Manager and manually but the outcome is the same – the tools are there but there is no option for syntax highlighting anymore. Any ideas?

![screen shot 2016-02-02 at 12 09 02 pm](https://cloud.githubusercontent.com/assets/6605496/12747683/c7c1ebca-c9a5-11e5-8814-5861bc94d4b3.png)

**Comment by 23maverick23** [comment]
Hey @klomontes . Thanks for using the package.

With the 3.0 release this past week, I have made the decision to remove/deprecate the syntax files as they were too much overhead to maintain.
http://sublime-jekyll.readthedocs.org/en/latest/faq.html#what-happened-to-all-the-syntax-files

If you'd like to reinstall them, I have moved them to a new repo where you can manually download and install in Sublime.
https://github.com/23maverick23/sublime-jekyll-syntaxes

There are also other packages out there that provide better highlighting.
https://github.com/siteleaf/liquid-syntax-mode
https://github.com/squ1b3r/Djaneiro/tree/master/Syntaxes

**Comment by klomontes** [comment]
It’s good to know there was not a problem with Sublime or package itself.

Thanks for an awesome plugin @23maverick23 :metal:
