### ISSUE TITLE
Error loading syntax file

### ISSUE THREAD

**Issue by zanderle** [23maverick23/sublime-jekyll#57]
After the 3.0 update, this error shows up every time I open Sublime. I use Sublime Text 3 on Mac Pro OSX 10.11.3

<img width="421" alt="screen shot 2016-02-04 at 02 26 28" src="https://cloud.githubusercontent.com/assets/5232693/12803523/1e12f780-caeb-11e5-8c7a-e313c64f9b58.png">

**Comment by 23maverick23** [comment]
Hey @zanderle . Thanks for using the package.

The 3.0 update deprecated the syntax files that were in 2.0. There were a few bugs in the highlighting with different themes, and it was starting to become difficult to maintain them myself.

Re: the error you're seeing - did you set the Jekyll syntax as the default for all markdown files per chance? If yes, you'll need to change that preference as the file is no longer part of the Jekyll package. If you still want to use the old syntax files, they aren't completely gone. I moved them to another repository - https://github.com/23maverick23/sublime-jekyll-syntaxes. You should be able to manually download them and load them into your `User` directory to continue using them.

**Comment by zanderle** [comment]
@23maverick23 thanks for the clarification!
