### ISSUE TITLE
Unable to resolve path

### ISSUE THREAD

**Issue by adeydas** [23maverick23/sublime-jekyll#65]
### Summary of issue
When trying to create a new post, the plugin is unable to resolve the path.

### System details

- System Platform? - OSX El Capitan
- Sublime Version? 3
- User or Project Settings? Project

### Sublime console output

Jekyll: Unable to resolve path information!

Please double-check that you have defined absolute paths to your Jekyll directories, or that you have enabled the `jekyll_auto_find_paths` setting.

If you have set your path settings correctly, please copy the console output and create a new issue.

**Comment by 23maverick23** [comment]
@adeydas Thanks for using the plugin.

Can you paste your project settings here, and copy the related **Jekyll** content from the ST console?

**Comment by adeydas** [comment]
Here's the project settings:
`{
	"jekyll_auto_find_paths": false,

	"folders":
	[
		{
			"follow_symlinks": true,
			"path": "/Users/abhishek/Documents/work/adeydas.github.io"
		}
	],

    "settings":
    {
        "Jekyll":
        {
            "posts_path": "/Users/abhishek/Documents/work/adeydas.github.io/_posts",
            "drafts_path": "/Users/abhishek/Documents/work/adeydas.github.io/_drafts",
            "uploads_path": "/Users/abhishek/Documents/work/adeydas.github.io/images",
        }
    }
}
`
And my console output:
`You've encountered an unexpected error, which likely means you've found a bug in our code. It would be great if you could copy any related console output into a new issue and send it over to us. We'll take a look and get back to you as soon as we can. Thanks!

error: Jekyll: Unable to resolve path information!

Please double-check that you have defined absolute paths to your Jekyll directories, or that you have enabled the `jekyll_auto_find_paths` setting.

If you have set your path settings correctly, please copy the console output and create a new issue.

Traceback (most recent call last):
  File "jekyll in /Users/abhishek/Library/Application Support/Sublime Text 3/Installed Packages/Jekyll.sublime-package", line 124, in _fn
  File "jekyll in /Users/abhishek/Library/Application Support/Sublime Text 3/Installed Packages/Jekyll.sublime-package", line 410, in title_input
  File "./posixpath.py", line 83, in join
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'
error: Jekyll: Oops! - this is a bit embarassing
		¯\_(ツ)_/¯ `

**Comment by cgorshing** [comment]
Some problems I noticed with my settings and paths are two things:

1) According to the source code, it looks for `jekyll_posts_path` and not `posts_path`, the later being deprecated. So my project settings look like:

    {
      "folders":
      [
        {
            "follow_symlinks": true,
            "path": "/Users/cgorshing/workspaces/project_name"
        }
    ],

    "settings":
    {
        "Jekyll":
        {
            "jekyll_auto_find_paths": false,
            "jekyll_posts_path": "/Users/cgorshing/workspaces/project_name/_posts",
            "jekyll_drafts_path": "/Users/cgorshing/workspaces/project_name/_drafts",
            "jekyll_uploads_path": "/Users/cgorshing/workspaces/project_name/uploads",
        }
      }
    }

2) Double check your paths fully. I had only checked up to `project_name`, and I was missing the actual `_posts` directory. As git doesn't track directories, and only files, I was messing around with a new repo to try it out on and I had removed the default post that comes with Jekyll, then created a branch (which didn't carry over the directory). Double check fully that your _posts directory exists.

**Comment by 23maverick23** [comment]
@adeydas 

I see 2 issues in your project settings:

1. You are using the old (pre Jekyll 3.0) settings keys. You can manually change them or run the Jekyll Utility for Project migration.
2. You are using the auto-find paths setting, but your image upload directory is `images` and should be `uploads` (per the Jekyll preferred standard).


Let me know if those 2 changes resolve your issue.

**Comment by irstacks** [comment]
Hi I've got what looks to be a similar issue this morning after trying to use the `Promote draft to post` and `Create post` commands, both of which functioned successfully last night immediately after installing the package and setting my settings, which I haven't edited since.

Here're my stats.

_Sublime console log_:
```
Traceback (most recent call last):
  File "jekyll in /Users/ia/Library/Application Support/Sublime Text 3/Installed Packages/Jekyll.sublime-package", line 124, in _fn
  File "jekyll in /Users/ia/Library/Application Support/Sublime Text 3/Installed Packages/Jekyll.sublime-package", line 410, in title_input
  File "./posixpath.py", line 83, in join
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'
error: Jekyll: Oops! - this is a bit embarassing
		¯\_(ツ)_/¯ 
```

_Project user settings_:
```
{
	"folders":
	[
		{
			"path": "/Users/ia/dev/nooblesoup"
		}

	],
	"settings":
	{
	    "Jekyll":
	    {
	        "posts_path": "/Users/ia/nooblesoup/_posts",
	        "drafts_path": "/Users/ia/nooblesoup/_drafts",
	        "uploads_path": "/Users/ia/nooblesoup/uploads",
	        "jekyll_datetime_format": "%Y-%m-%d %H:%M:%S"
	    }
	}

}
```

Thanks all.

**Comment by adeydas** [comment]
Looks like jekyl_ did the trick. This is my config file that works:

`  {
	"folders":
	[
		{
			"follow_symlinks": true,
			"path": "/Users/abhishek/Documents/work/adeydas.github.io"
		}
	],

    "settings":
    {
        "Jekyll":
        {
            "jekyll_auto_find_paths": false,
            "jekyll_posts_path": "/Users/abhishek/Documents/work/adeydas.github.io/_posts",
            "jekyll_drafts_path": "/Users/abhishek/Documents/work/adeydas.github.io/_drafts",
            "jekyll_uploads_path": "/Users/abhishek/Documents/work/adeydas.github.io/uploads",
            "jekyll_datetime_format": "%Y-%m-%d %H:%M:%S",
        }
    }
}
`

**Comment by 23maverick23** [comment]
@irstacks Did you restart ST after changing your settings? I don't see why you would be getting that particular error using the new/correct settings keys. Please let me know.

**Comment by irstacks** [comment]
Hi @23maverick23  - yep, have restarted ST and computer too. 
Made sure all specified folders are there.
Same error.

Project settings are still
```
{
	"folders":
	[
		{
			"path": "/Users/ia/dev/nooblesoup"
		}

	],
	"settings":
	{
	    "Jekyll":
	    {
		// "jekyll_auto_find_paths": false, <-- have tried with and without. no luck.
	        "jekyll_posts_path": "/Users/ia/nooblesoup/_posts",
	        "jekyll_drafts_path": "/Users/ia/nooblesoup/_drafts",
	        "jekyll_uploads_path": "/Users/ia/nooblesoup/uploads",
	        "jekyll_datetime_format": "%Y-%m-%d %H:%M:%S"
	    }
	}

}
```

**Comment by irstacks** [comment]
@23maverick23 ! Got it. I'm a beanhead. My paths were wrong -- notice I forgot `/dev/' in there. Dumb. Works great now. 
And thank you.

**Comment by 23maverick23** [comment]
Glad you were able to get it working.
