### ISSUE TITLE
Notifying the end user about setting path information via unhandled exception isn't obvious

### ISSUE THREAD

**Issue by valerykalashnikov** [23maverick23/sublime-jekyll#66]
### Summary of issue
How to reproduce:

1. Install package using Package Control.
2. Press `cmd + shift + p` and type `Jekyll: New post`
3. Type the name of your new post and press enter
4. Oooops

![jekyll-oops](https://cloud.githubusercontent.com/assets/1069061/13659847/34a5bc96-e6af-11e5-8fdd-5f4aff1f0e04.png)

Setting `jekyll_auto_find_paths` option to `true` solves the problem, but notifying the user via an unhandled exception isn't obvious, I think.

### System details

- System Platform: OS X 10.9.5
- Sublime Version? 3 build 3103
- User or Project Settings?

### Sublime console output
error: Jekyll: Unable to resolve path information!

Please double-check that you have defined absolute paths to your Jekyll directories, or that you have enabled the `jekyll_auto_find_paths` setting.

If you have set your path settings correctly, please copy the console output and create a new issue.

Traceback (most recent call last):
  File "jekyll in /Users/valerykalashnikov/Library/Application Support/Sublime Text 3/Installed Packages/Jekyll.sublime-package", line 124, in _fn
  File "jekyll in /Users/valerykalashnikov/Library/Application Support/Sublime Text 3/Installed Packages/Jekyll.sublime-package", line 410, in title_input
  File "./posixpath.py", line 83, in join
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'
error: Jekyll: Oops! - this is a bit embarassing
    ¯\_(ツ)_/¯ 

You've encountered an unexpected error, which likely means you've found a bug in our code. It would be great if you could copy any related console output into a new issue and send it over to us. We'll take a look and get back to you as soon as we can. Thanks!

**Comment by 23maverick23** [comment]
@valerykalashnikov Thanks for using the package. I'll take a look at improving the error checking for path exceptions and see if there is a more graceful way of disabling the package commands if a path isn't found.

**Comment by mengkheang** [comment]
I have the same problem to when I try to create draft but I already set jekyll_auto_find_paths option to true

**Comment by 23maverick23** [comment]
Should be addressed in v3.0.3 (fd33a94).
