### ISSUE TITLE
Can't Promote Drafts with Seemingly Correct Settings

### ISSUE THREAD

**Issue by Merovex** [23maverick23/sublime-jekyll#68]
### Summary of issue

When attempting to Promote Draft, I get the following error:

> Jekyll: Unable to resolve path information!

> Please double-check that you have defined absolute paths to your Jekyll directories, or that you have enabled the `jekyll_auto_find_paths` setting.

> If you have set your path settings correctly, please copy the console output and create a new issue.

### System details

- System Platform? Mac OSX
- Sublime Version? Stable Build 3114
- User or Project Settings?

```
{
  "folders":
  [
      {
          "follow_symlinks": true,
          "path": "/valid/path/to/"
      }
  ],

  "settings":
  {

    "Jekyll":
      {
        "jekyll_posts_path": "/valid/path/to/_posts",
        "jekyll_drafts_path": "/valid/path/to/_drafts",
        "jekyll_uploads_path": "/valid/path/to/uploads",
        "jekyll_auto_find_paths": true,
        "jekyll_debug": true
      }
  }
}
```

### Sublime console output

error: Jekyll: Unable to resolve path information!

Please double-check that you have defined absolute paths to your Jekyll directories, or that you have enabled the `jekyll_auto_find_paths` setting.

If you have set your path settings correctly, please copy the console output and create a new issue.

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 553, in run_
    return self.run()
  File "jekyll in /Users/bwilson/Library/Application Support/Sublime Text 3/Installed Packages/Jekyll.sublime-package", line 889, in run
  File "jekyll in /Users/bwilson/Library/Application Support/Sublime Text 3/Installed Packages/Jekyll.sublime-package", line 434, in list_files
  File "./python3.3/genericpath.py", line 18, in exists
TypeError: can't specify None for path argument

**Comment by Merovex** [comment]
The TypeError message should be trapped with the variable sought sent to the console for better error handling. If it would tell me what path is None, I could fix it myself.

**Comment by 23maverick23** [comment]
Thanks for using the package @Merovex 

I agree that the path exception is a bit generic at the moment, and like your idea of throwing a more specific message into the stack trace. Let me see what I can do to re-work that part and push it into the next release.

**Comment by Merovex** [comment]
Thanks. In the interim, how can I promote a draft?

On Wed, Jun 15, 2016 at 8:35 PM, Ryan Morrissey <notifications@github.com>
wrote:

> Thanks for using the package @Merovex <https://github.com/Merovex>
>
> I agree that the path exception is a bit generic at the moment, and like
> your idea of throwing a more specific message into the stack trace. Let me
> see what I can do to re-work that part and push it into the next release.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/23maverick23/sublime-jekyll/issues/68#issuecomment-226358848>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAGpM9X8RAixBgYBsCSCs3wsw006px0pks5qMJo8gaJpZM4Izi-H>
> .
>



-- 
Ambuletis Digne,
Ben Wilson

We complain because we forget.

**Comment by 23maverick23** [comment]
If you are hard coding your paths (b/c they aren't within your project structure), you should remove `jekyll_auto_find_paths`, or set to false for now.

You also need to make sure that your paths are full, absolute paths and not partial or relative to the project root.

The stack trace you pasted typically indicates that the `jekyll_auto_find_paths` method ran, couldn't find your `_drafts` or `_posts` directory, and returned `None` for the path argument, which then threw a `MissingPathException`.

I'll try and push an update tonight which may help you determine what is specifically wrong.

**Comment by Merovex** [comment]
Dude, you closed this prematurely. The title says I can't promote. I still can't promote.

I did what you said to do, and I am still getting the error. Specifically:

* Set "jekyll_auto_find_paths": false (rebooted Subl) and got the error
* Removed "jekyll_auto_find_paths" (rebooted Subl) and got the error
* Tested to confirm that all my absolute path variables were accurate.

I got an update, but the error messages are no more informative:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 553, in run_
    return self.run()
  File "jekyll in /Users/<redacted>/Library/Application Support/Sublime Text 3/Installed Packages/Jekyll.sublime-package", line 889, in run
  File "jekyll in /Users/<redacted>/Library/Application Support/Sublime Text 3/Installed Packages/Jekyll.sublime-package", line 434, in list_files
  File "./python3.3/genericpath.py", line 18, in exists
TypeError: can't specify None for path argument
```

But, I see the test is done at the beginning, and is hidden by a flurry of other reports from Subl.

```
error: Jekyll: Unable to resolve path information!

Path is null for "_drafts" directory.

Please double-check that you have defined absolute paths to your Jekyll directories, or that you have enabled the `jekyll_auto_find_paths` setting.

If you have set your path settings correctly, please copy the console output and create a new issue.
```

Now that I'm looking into it. The method in question is found in Python.py:421-453, and is specifically failing at 434. `if os.path.exists(path) and os.path.isdir(path)` This is consistent with the specific error "TypeError: can't specify None for path argument"

When I suggested creating a specific error, it would have been a try/catch block around this subroutine. Now, looking at line 889 and its method (below) it would appear that the drafts_path_string is None. Ideally, at this line, you would check for the presence of the String here, and if it failed dump a log message that said "drafts_path_string is undefined."

In my case, that string is defined.

```
def run(self):
        d_path = self.drafts_path_string()
        self.list_files(d_path)

        if ST3:
            self.window.show_quick_panel(
                self.item_list,
                self.on_done,
                on_highlight=self.on_highlight
            )

        else:
            self.window.show_quick_panel(
                self.item_list,
                self.on_done
            )
```

**Comment by Merovex** [comment]
There's no Lint to confirm the settings are right. Why not do a dump of the values?

**Comment by 23maverick23** [comment]
The MissingPathException message of "path is null" means either that you haven't defined a path, or the package didn't find one in your settings hierarchy.

If you're using Project settings (which I think you are), open your project and try typing the following into the console to confirm the value you are passing as a drafts path:
```python
view.settings().get('Jekyll').get('jekyll_drafts_path')
```

If you are using User settings, you can try:
```python
sublime.load_settings('Jekyll.sublime-settings').get('jekyll_drafts_path')
```

The package will attempt to find a project settings key first, and fall back to a user settings key before returning `None` and raising an exception.

**Comment by Merovex** [comment]
On Thu, Jun 16, 2016 at 8:42 AM, Ryan Morrissey <notifications@github.com>
wrote:

> view.settings().get('Jekyll').get('jekyll_drafts_path')
>
>
​How do I dump the view.settings().get('Jekyll')? I ask because when I post
the above recommendation I get an error:

```
>>> view.settings().get('Jekyll').get('jekyll_drafts_path')
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'get'​
​```​

So the issue isn't that the directories aren't accurate, it's that it's not
being set. ​Here is the sum of my project settings:

```

{
  "folders":
  [
      {
          "follow_symlinks": true,
          "path": "/path/"
      }
  ],

  "settings":
  {

    "Jekyll":
      {
        "jekyll_posts_path": "/path/_posts/",
        "jekyll_drafts_path": "/path/_drafts/",
        "jekyll_uploads_path": "/path/uploads/",
        "jekyll_auto_find_paths": false,
        "jekyll_debug": true
      }
  }
}
```​


-- 
Ambuletis Digne,
Ben Wilson

We complain because we forget.

**Comment by 23maverick23** [comment]
Ok - this is helpful. Your settings format looks correct from here but I guess you could have formatting or spacing issues?

Dumb question here, so don't take offense, but are you sure your project is actually open in Sublime (and you're not just in the directory of your Jekyll site in the sidebar)? You can also use `view.settings().has(some_key)` to verify the key exists before throwing the `AttributeError` you pasted.

AFAIK, ST doesn't have an API method for dumping all available settings keys [see this forum post](https://forum.sublimetext.com/t/how-to-a-serialize-st-settings-object/8789/2).


FWIW, I pasted your settings above into a dummy project and it works fine for me.

```json
// testproject.sublime-project
{
    "folders": [
        {
            "follow_symlinks": true,
            "path": "/path/"
        }
    ],
    "settings": {
        "Jekyll": {
            "jekyll_auto_find_paths": false,
            "jekyll_debug": true,
            "jekyll_drafts_path": "/path/_drafts/",
            "jekyll_posts_path": "/path/_posts/",
            "jekyll_uploads_path": "/path/uploads/"
        }
    }
}
```

```python
view.settings().get('Jekyll')
# {'jekyll_drafts_path': '/path/_drafts/', 'jekyll_uploads_path': '/path/uploads/', 'jekyll_auto_find_paths': False, 'jekyll_debug': True, 'jekyll_posts_path': '/path/_posts/'}

view.settings().get('Jekyll').get('jekyll_drafts_path')
# '/path/_drafts/'
```

**Comment by Merovex** [comment]
No offense taken. I am effectively AFK until tomorrow due to travel.

This has only occurred recently..but I will check your points when home.
