### ISSUE TITLE
Option to choose file extension

### ISSUE THREAD

**Issue by thenoelforte** [23maverick23/sublime-jekyll#73]
While I realize that Gruber's post on why `.markdown` should be the preferred extension when writing posts, there are a lot of places where the much shorter `.md`extension are used including for GitHub, GitLab, and BitBucket README files, which includes the README in this repository. For those of us who prefer to use the shorter extension to maintain consistency in our work, would it be possible to have `sublime-jekyll` create new posts and drafts with a user-specified extension, or at least have the option to choose between `.md` and `.markdown`? Does this functionality already exist?

**Comment by 23maverick23** [comment]
Certainly doable. I can look at adding this to a future update.

**Comment by Fastidious** [comment]
👍 for .md support.
