### ISSUE TITLE
Sublime Text 3 Error Building C Code

### ISSUE THREAD

**Issue by Lorybat1998UCD** [23maverick23/sublime-jekyll#74]
###

I have tried using this on all of my platforms, but I still can't get the sublime text editor to build my code for me in the console and execute it. I therefore have to run a cmd/terminal every time to test my applications. I am getting the following error on mac (latest), and a similar one for Windows (10 Enterprise x64) and Linux (Debian latest). Please find attached the error code from my mac, I will upload a copy of the one Windows and Linux are throwing back tomorrow when I have access to my win and Debian machines at work.

If further details/clarifications are necessary, please let me know.

Thank you in advance for your kind help.

### System details

- Mac OS X 10.12.1 (Sierra)
- Sublime Text 3

### Sublime console output
```
[Errno 13] Permission denied
[cmd: ['./']]
[dir: /Applications/Sublime Text.app/Contents/MacOS]
[path: /usr/bin:/bin:/usr/sbin:/sbin]
[Finished]
```

**Comment by 23maverick23** [comment]
I don't understand what this has to do with the sublime-jekyll package for ST.

Is this somehow related to the [example build system in the documentation](http://sublime-jekyll.readthedocs.io/en/latest/builds.html)? Please clarify.
