### ISSUE TITLE
Post Promotion TypeError

### ISSUE THREAD

**Issue by bwarren2** [23maverick23/sublime-jekyll#75]
### Summary of issue
When I try to promote a draft to a post, I get this error in the Sublime console:
```
Traceback (most recent call last):
  File "jekyll in /home/ben/.config/sublime-text-3/Installed Packages/Jekyll.sublime-package", line 874, in on_done
  File "./python3.3/posixpath.py", line 83, in join
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'
```

If there are some tips on getting hacking at/debugging installed packages, I can try to isolate the error myself and make a PR.  The problem is clearly [here](https://github.com/23maverick23/sublime-jekyll/blob/master/jekyll.py#L874), but the relevant file is in a format I don't know how to edit/debug.  
(
```
head -n 1 /home/ben/.config/sublime-text-3/Installed\ Packages/Jekyll.sublime-package 
PKdj�I�����>LICENSEURK��0��W�8�J������Lb�!���cH
                                                      qbd�"�}g�ݕ"¼��Lto`%4�5c0���c�d�t���Gxh�ۗ��?��P�f���ކ`�IRĿ֍`�ƛ����R�{c����0)D�x����.6v��h�;��#Lp�xi����\kăε��c�oo�!��Y}��=N$�i�cB��\l��9�7!z�F�M�p�H�ky�G{g��i	A�s@�3������f�u:��:Kлs�d���Ӕ||v�B��{���n�!�'Zh���x�һ#|p�+ڟ���f���,M���i#e�}���]�Z��Β��3I4����k&/��.�ԛ:�����R�Ծ3��!�SɫO�C��[��������^��/9�r�7Lq5TJ����0c5Ƴ6B/�Zv(V�-��r
            �D���W��5H��U�9Qf�:�3�q���9
                                        ��TK �;��5���ʖ��(�ަ��D�d!0���"[LA�V��9�[�r����x���s�_0�zɊb�bkT�&}���J</5,e�sL�9*c���D�����U
```
)

### System details

- System Platform?
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
```
- Sublime Version?
```
subl -v
Sublime Text Build 3126
```
- User or Project Settings?
```
{
	"folders":
	[
		{
			"path": "."
        }
    ],
    "settings": {
       // This should point to your "_posts" directory.
        // NOTE: This should be an absolute path. Also, the path should
        // match your system convention. For example, Windows machines should
        // have a path similar to "C:\\Users\\username\\site\\_posts".
        // *nix systems should have a path similar to "/Users/username/site/_posts".
        "jekyll_posts_path": "/home/ben/Projects/static_sites/lanyon/_posts",

        // This should point to your "_drafts" directory.
        // NOTE: This should be an absolute path. Also, the path should
        // match your system convention. For example, Windows machines should
        // have a path similar to "C:\\Users\\username\\site\\_drafts".
        // *nix systems should have a path similar to "/Users/username/site/_drafts".
        "jekyll_drafts_path": "/home/ben/Projects/static_sites/lanyon/_drafts",

        // Optionally override the location of the templates directory.
        // Make sure your override directory is named "_templates", especially
        // if you plan on using the "jekyll_auto_find_paths" setting.
        // NOTE: This should be an absolute path. Also, the path should
        // match your system convention. For example, Windows machines should
        // have a path similar to "C:\\Users\\username\\site\\templates".
        // *nix systems should have a path similar to "/Users/username/site/_templates".
        "jekyll_templates_path": "",

        // If you have multiple Jekyll blogs, but don't use Sublime Projects,
        // you can optionally have sublime-jekyll look for the `_posts` or `_drafts`
        // or `uploads` folders open in your sidebar. This should have a value of
        // true or false.
        "jekyll_auto_find_paths": false,

        // This should point to the default uploads directory.
        // NOTE: This should be an absolute path. Also, the path should
        // match your system convention. For example, Windows machines should
        // have a path similar to "C:\\Users\\username\\site\\uploads".
        // *nix systems should have a path similar to "/Users/username/site/uploads".
        "jekyll_uploads_path": "",

        // This string value should represent the baseurl for the uploads directory.
        // For example, if your uploads directoy is "uploads/" and you have an image
        // called "image.png", then the output of inserting the image in your post
        // would be "<uploads_baseurl>/uploads/image.png", with <uploads_baseurl>
        // replaced by its value.
        // If you wish to have an absolute link and you have "url" defined in your jekyll
        // config file, then you can set the value to: "{{ site.url }}/{{ site.baseurl }}"
        "jekyll_uploads_baseurl": "{{ site.baseurl }}",

        // This determines the file type for new drafts and posts. Can be set to one of
        // three accepted values: "Markdown", "Textile" or "HTML".
        // NOTE: We use `.markdown` as the standard file extension for Markdown files as
        // suggested by John Gruber, developer of Markdown, in his blog post here:
        // http://daringfireball.net/linked/2014/01/08/markdown-extension
        "jekyll_default_markup": "Markdown",

        // This determines if sublime-jekyll should send deleted drafts, posts and templates to
        // the system trash/recycling bin, or immediately purge them from disk. The
        // default value is `false` which means files are purged immediately.
        "jekyll_send_to_trash": false,

        // ************************************************************************************
        // If for some reason you want to change the way either the date
        // or the datetime string is formatted, you can override those formats
        // here using valid Python datetime.strftime() format codes.
        //
        // If you need a refresher on these codes, have a look at the Python
        // documentation found here:
        //
        // http://docs.python.org/2/library/datetime.html#strftime-and-strptime-behavior
        // ************************************************************************************

        // A valid Python strftime string
        "jekyll_date_format": "%Y-%m-%d",

        // A valid Python strftime string
        "jekyll_datetime_format": "%Y-%m-%d %H:%M:%S",

        // ************************************************************************************
        // Package Debug
        // ************************************************************************************

        // If set to true, will print Jekyll debug information to the Sublime Text console.
        "jekyll_debug": true,

        // If set to true, all Jekyll Utility commands will be hidden from menus and the Command Palatte.
        "jekyll_utility_disable": false
    }
}
```
```
{
	"caret_style": "solid",
	"color_scheme": "Packages/User/SublimeLinter/Monokai Extended (SL).tmTheme",
	"detect_slow_plugins": true,
	"ensure_newline_at_eof_on_save": true,
	"folder_exclude_patterns":
	[
		"node_modules"
	],
	"font_face": "Ubuntu Mono",
	"font_options":
	[
		"subpixel_antialias",
		"no_bold"
	],
	"font_size": 15,
	"ignored_packages":
	[
		"Vintage"
	],
	"line_padding_bottom": 0,
	"line_padding_top": 0,
	"rulers":
	[
		72,
		79
	],
	"theme": "SoDaReloaded Dark.sublime-theme",
	"translate_tabs_to_spaces": true,
	"trim_trailing_white_space_on_save": true,
	"wide_caret": true,
	"word_wrap": true,
	"wrap_width": 80
}
```
### Sublime console output
```
Traceback (most recent call last):
  File "jekyll in /home/ben/.config/sublime-text-3/Installed Packages/Jekyll.sublime-package", line 874, in on_done
  File "./python3.3/posixpath.py", line 83, in join
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'
```

**Comment by bwarren2** [comment]
Chat tells me these are zip files.  Is there interest in a `jekyll_base_path` variable, which names an env var to try prepending paths with?  (Ie, if that setting is not "", treat the import paths as relative to that env var's value?)

**Comment by 23maverick23** [comment]
@bwarren2 First off, thanks for using the package and posting feedback!

Can you please confirm that you are in an active ST project when attempting to promote the draft? This error typically only happens if you have your settings in a project file, however you aren't in an active project (see #68 ).

Can you also try restarting ST3 with sublime-jekyll debug setting enabled, and copying/pasting the ST console output? Sometimes that can further nail down where there are issues we can fix.

**Comment by bwarren2** [comment]
Update: I had to purge my settings/cache because some over-aggressive
autocomplete indexing was slowing down everything.  Since reimplementing, I
have set these project settings in a project I am actively working on, but
the _drafts variable is seen as unset when I try to create a draft.  What
is the best way to check the currently-seen settings in Sublime?  Is there
something I can poke in the terminal?

(Sorry to make this such a hassle!)

{
    "folders":
    [
        {
            "path": "."
        }
    ],
        "settings": {
       // This should point to your "_posts" directory.
        // NOTE: This should be an absolute path. Also, the path should
        // match your system convention. For example, Windows machines
should
        // have a path similar to "C:\\Users\\username\\site\\_posts".
        // *nix systems should have a path similar to
"/Users/username/site/_posts".
        "jekyll_posts_path": "/home/ben/Projects/static_sites/proj/_posts",

        // This should point to your "_drafts" directory.
        // NOTE: This should be an absolute path. Also, the path should
        // match your system convention. For example, Windows machines
should
        // have a path similar to "C:\\Users\\username\\site\\_drafts".
        // *nix systems should have a path similar to
"/Users/username/site/_drafts".
        "jekyll_drafts_path":
"/home/ben/Projects/static_sites/proj/_drafts",

        // Optionally override the location of the templates directory.
        // Make sure your override directory is named "_templates",
especially
        // if you plan on using the "jekyll_auto_find_paths" setting.
        // NOTE: This should be an absolute path. Also, the path should
        // match your system convention. For example, Windows machines
should
        // have a path similar to "C:\\Users\\username\\site\\templates".
        // *nix systems should have a path similar to
"/Users/username/site/_templates".
        "jekyll_templates_path": "",

        // If you have multiple Jekyll blogs, but don't use Sublime
Projects,
        // you can optionally have sublime-jekyll look for the `_posts` or
`_drafts`
        // or `uploads` folders open in your sidebar. This should have a
value of
        // true or false.
        "jekyll_auto_find_paths": false,

        // This should point to the default uploads directory.
        // NOTE: This should be an absolute path. Also, the path should
        // match your system convention. For example, Windows machines
should
        // have a path similar to "C:\\Users\\username\\site\\uploads".
        // *nix systems should have a path similar to
"/Users/username/site/uploads".
        "jekyll_uploads_path": "",

        // This string value should represent the baseurl for the uploads
directory.
        // For example, if your uploads directoy is "uploads/" and you have
an image
        // called "image.png", then the output of inserting the image in
your post
        // would be "<uploads_baseurl>/uploads/image.png", with
<uploads_baseurl>
        // replaced by its value.
        // If you wish to have an absolute link and you have "url" defined
in your jekyll
        // config file, then you can set the value to: "{{ site.url }}/{{
site.baseurl }}"
        "jekyll_uploads_baseurl": "{{ site.baseurl }}",

        // This determines the file type for new drafts and posts. Can be
set to one of
        // three accepted values: "Markdown", "Textile" or "HTML".
        // NOTE: We use `.markdown` as the standard file extension for
Markdown files as
        // suggested by John Gruber, developer of Markdown, in his blog
post here:
        // http://daringfireball.net/linked/2014/01/08/markdown-extension
        "jekyll_default_markup": "Markdown",

        // This determines if sublime-jekyll should send deleted drafts,
posts and templates to
        // the system trash/recycling bin, or immediately purge them from
disk. The
        // default value is `false` which means files are purged
immediately.
        "jekyll_send_to_trash": false,

        //
************************************************************************************
        // If for some reason you want to change the way either the date
        // or the datetime string is formatted, you can override those
formats
        // here using valid Python datetime.strftime() format codes.
        //
        // If you need a refresher on these codes, have a look at the Python
        // documentation found here:
        //
        //
http://docs.python.org/2/library/datetime.html#strftime-and-strptime-behavior
        //
************************************************************************************

        // A valid Python strftime string
        "jekyll_date_format": "%Y-%m-%d",

        // A valid Python strftime string
        "jekyll_datetime_format": "%Y-%m-%d %H:%M:%S",

        //
************************************************************************************
        // Package Debug
        //
************************************************************************************

        // If set to true, will print Jekyll debug information to the
Sublime Text console.
        "jekyll_debug": true,

        // If set to true, all Jekyll Utility commands will be hidden from
menus and the Command Palatte.
        "jekyll_utility_disable": false
    }
}

**Comment by 23maverick23** [comment]
If you are defining **Project specific** settings for this plugin, you need to make sure you follow the format defined here: http://sublime-jekyll.readthedocs.io/en/latest/settings.html#project-settings.

All the sublime-jekyll settings are stored inside a `Jekyll` key (which I believe you are missing above). I've re-written what your `.sublime-project` settings should look like below. Can you update and see if this resolves the issue?

```json
{
    "folders":
    [
        {
            "path": "."
        }
    ],
    "settings": {
        "Jekyll": {
            "jekyll_posts_path": "/home/ben/Projects/static_sites/proj/_posts",
            "jekyll_drafts_path": "/home/ben/Projects/static_sites/proj/_drafts",
            "jekyll_templates_path": "",
            "jekyll_auto_find_paths": false,
            "jekyll_uploads_path": "",
            "jekyll_uploads_baseurl": "{{ site.baseurl }}",
            "jekyll_default_markup": "Markdown",
            "jekyll_send_to_trash": false,
            "jekyll_date_format": "%Y-%m-%d",
            "jekyll_datetime_format": "%Y-%m-%d %H:%M:%S",
            "jekyll_debug": true,
            "jekyll_utility_disable": false
        }
    }
}
```

**Comment by bwarren2** [comment]
You are absolutely right, I don't know how I missed that.  My apologies.
Thank you for being so helpful and kind!

**Comment by 23maverick23** [comment]
Happy to help! Enjoy.
