### ISSUE TITLE
Allow for txt file extension

### ISSUE THREAD

**Issue by dylan-k** [23maverick23/sublime-jekyll#86]
It's great to have some options for file extension but would it be possible to add one for .txt?

https://github.com/23maverick23/sublime-jekyll/commit/47ee957d4c2cc87ece39b9da331a02c9fe9315df#r26451488

**Comment by 23maverick23** [comment]
First off, thanks for using the package. I appreciate it!

What's your specific use case? Jekyll posts and pages are really supposed to be written in Markdown (with support for Textile using a plugin, or HTML if needed). How and why would you be using a <kbd>.txt</kbd> file? It's trivial to add support but curious how "Jekyll-ian" it is.

**Comment by dylan-k** [comment]
Thank you for making this package. It really is useful!

iirc, Jekyll and its markdown parsers have always allowed users to indicate which file extensions to work on, and so I have. I prefer the .txt file extension in some cases because it it shorter and because it is even more ubiquitous than markdown. This is also useful in cases where the txt files are not only for use with Jekyll.

**Comment by 23maverick23** [comment]
I decided to support this enhancement via a `Plain text` settings option, which is now available for the `"jekyll_default_markup"` settings key. Setting that key to `"Plain text"` (vs. `"Markdown"`) will create new drafts/posts using the `.txt` file extension. Additionally, the package will now show `.txt` files inside your `_drafts` and `_posts` directories for opening and promoting via the package commands.

Thanks again @dylan-k for using the package and contributing to its development.
