### ISSUE TITLE
"Insert Upload Tag" paths normalization needed

### ISSUE THREAD

**Issue by aklef** [23maverick23/sublime-jekyll#92]
### Summary of issue
The menu command listed as "Insert Upload Tag" will insert into my markdown document a relative path with backslashes. This is wrong.

For example You would expect  `<uploads_baseurl>/uploads/image.png` as the output when selecting `image.png` for upload. However on windows, the output is `<uploads_baseurl>/uploads\image.png`

Thus, paths normalization is needed.

### System details

- System Platform? 
Windows 7 in my case

- Sublime Version? 
Problem should exist in any Sublime version but I happen to be running v3208

**Comment by 23maverick23** [comment]
Looks like the path separator is hard coded at [line 1205](https://github.com/23maverick23/sublime-jekyll/blob/master/jekyll.py#L1205) into the link string instead of using `os.path.join` which is used elsewhere and handles this correctly. Should be an easy fix (once I have time to push an update).

**Comment by aklef** [comment]
> the path separator is hard coded at [line 1205](https://github.com/23maverick23/sublime-jekyll/blob/master/jekyll.py#L1205) into the link string

I don't think that's the issue, as it is hardcoded the right way for the web (we _want_ forwardslashes)

The issues stems from the `relative_path` appended to the end of the  `link_str`.

The `relative_path` needs to have its backslashes removed and replaced by forwardslahes...

Is that right?

**Comment by 23maverick23** [comment]
@aklef I don't actually use this feature (nor did I code it), so maybe you can help me understand it. I find a file that I want to link to in my markdown, and when I add it to my markdown, I *always* want it to use POSIX format (vs. Windows format) so that it conforms to web standards? Right now, the `relative_path` feature is returning the `os.sep` for Windows which messes up the web path.

**Comment by 23maverick23** [comment]
If the above is correct, we will need to look at [line 1202](https://github.com/23maverick23/sublime-jekyll/blob/master/jekyll.py#L1202).

We could potentially do this using `posixpath.relpath` instead so that we always return forward slashes regardless of OS...

**Comment by aklef** [comment]
Aha. I've done some digging and there's lots to unpack here.

Clarifications:
1. My `jekyll_uploads_path` directory is different from my `jekyll_uploads_baseurl`, as may be the case for others. I do this for a few reasons, mainly: I don't want to version control my entire image folder along with my site, only the images that I choose. My point is, this is a feature and we should support this ability
2. The "Insert Upload Tag" snippet doesn't know/care where the actual file is, nor if the destination URL it creates will point to an actual file.

Which leads to me the conclusion that... this whole path business shouldn't be necessary. All we want is the chosen file's name to be appended to our site's `jekyll_uploads_baseurl`.

I will update the relevant docs for clarity and push a PR soon
